tools:
  external_code_coverage:
    runs: 2
  php_code_sniffer: true
  php_sim: true
  php_changetracking: true
  php_mess_detector: true
  php_pdepend: true
  php_analyzer: true
  sensiolabs_security_checker: true
